application: main
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /index-style\.css
  static_files: index-style.css
  upload: index-style\.css

- url: /index-script\.js
  static_files: index-script.js
  upload: index-script\.js

- url: /scoreboard\.html
  static_files: scoreboard.html
  upload: scoreboard\.html

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
